### PR TITLE
Fringe indicator of wrap status/search start position

### PR DESCRIPTION
**Pull request by astoff**
`isearch-mb-fringe-indicator-mode` shows an arrow pointing to the search start position. It changes color after wrap. Unfortunately this only works well in the standard Isearch, because we can't compute the window boundaries after letting `inhibit-redisplay` be nil.

@minad Does it look any good to you?

### CODE REVIEW

**Comment by minad** [comment]
Fringe indicator is a good idea :) Didn't think of that. I will give it a try!

**Comment by minad** [comment]
I tried this but I don't see anything. Maybe a theme thing? I activated both isearch-mb-mode and the fringe mode. Is a separate mode necessary, why not make it part of isearch-mb-mode?

EDIT: Now I see it. It is at the right fringe, too subtle and does not feel very useful.

**Comment by astoff** [comment]
Just in case, I pushed a variant which is on the same line as the cursor, and on the left.

**Comment by minad** [comment]
Yes, having something on the line of the cursor is preferable. I will give this a test. But I am mostly satisfied with your package now, it looks all good, except #12. Did you already ask for inclusion on ELPA?

**Comment by astoff** [comment]
I just wrote in one of those long email threads that I want to submit to ELPA. How did you formalize your submissions?

**Comment by minad** [comment]
https://lists.gnu.org/archive/html/emacs-devel/2021-04/msg00177.html

**Comment by minad** [comment]
I tried your new fringe indicator on the left. While it looks better, I don't think that it is that useful. Now I find even a bit distracting. I would probably not make this feature part of the package. 

Instead you may want to reconsider the wrap around messages (#7), but I think I would also be okay without that feature and the less verbose prompt. It just feels a bit less familiar since I am accustomed to these messages from plain Isearch. Then an improved mode line indicator is something I am certain I would like to have (#6).

But as I wrote I am pretty happy with the status quo now :)

**Comment by astoff** [comment]
I've added a version of this functionality as a wiki entry. There's not place for it in the package itself.

**Pull request closed without merging**
