### PR TITLE
Set cursor-in-non-selected-windows=t

### PR DESCRIPTION
**Pull request by minad**

### CODE REVIEW

**Comment by astoff** [comment]
Wait, t is the default value `cursor-in-non-selected-windows`, so what is this supposed to do?

The default cursor is of block style; filled in in selected windows and hollow otherwise. In `isearch-mb-mode`, the cursor in the search buffer becomes hollow because the minibuffer is the selected window. This seemed sufficient to me because the `isearch` face is very prominent anyway. Is this about making things work better with a custom theme, perhaps?

I like Consult's yellow cursor and would even make it the same here for consistency, but I think it would look cacophonous together with the isearch magenta and cyan faces.

**Comment by minad** [comment]
In my config I set the the variable globally to nil. I propose to override this here to ensure that the setting is t in any case, such that your package is compatibile with odd configs.

**Comment by astoff** [comment]
Hum, by setting this variable one gets exactly what one asks for, and in Isearch specifically the cursor is kind of superfluous, because there's already the flashy match overlay. (In Consult the story is a bit different, of course).

Maybe here you should wrap `isearch-mb--session` yourself using the glorious `consult--local-let`?

**Comment by minad** [comment]
Why not bind the variable here? I don't see a downside of doing that. Of course I can use my own wrapper/let-binding.

This is a bit of a policy thing. My policy is to set required variables in Consult as long as I consider the modification of the variable in question to be a reasonable thing. This is a thin line, but if a package can handle many different customization scenarios that's a good thing. For example you also set `enable-recursive-minibuffers=t` since otherwise your package wouldn't work.

It is the question if you consider setting `cursor-in-non-selected-window=nil` globally a reasonable setting. For me this setting worked pretty well, I never noticed problems with it. Your package is the first which introduced an issue, since you transfer the Isearch control from the buffer to the minibuffer. Therefore I am claiming that the setting `cursor-in-non-selected-window=t` is required for your package and therefore I propose to bind it to non-nil here. I also claim that let-binding the variable is non-intrusive since it will be active only during the Isearch.

`consult--local-let` would be more correct, but since Isearch-mb doesn't really work well with recursive editing (you cannot nest arbitrary recursive search sessions, #3), using a simple let binding is good enough.

**Comment by minad** [comment]
I pushed a modification which ensures that the variable is non-nil but does not intrusively overwrite it with t, since the user may have a custom configuration like hollow, bar etc. Is it better like this?

**Comment by astoff** [comment]
This change makes a cursor appear in all windows, not just the search window, which is distracting if you have `(setq-default cursor-in-non-selected-windows nil)` in your config.

I'm also not convinced this is a universally desired setting. In fact, Ctrlf lets `cursor-in-non-selected-windows=nil` during a search, which I find a misguided thing to do by default, but in any case indicates that some people might still prefer not to see a cursor.

My impression here is that whoever has `cursor-in-non-selected-windows=nil`  by default would also want to set `isearch-repeat-on-direction-change=t`. This is only available in Emacs 28, unfortunately.

**Comment by minad** [comment]
> This change makes a cursor appear in all windows, not just the search window, which is distracting if you have (setq-default cursor-in-non-selected-windows nil) in your config.

That's right. But I think that's a fair price to pay. An overlay would be the better solution as I am using in `consult-line`, but that's kind of a heavy addition to Isearch-mb, isn't it?

> I'm also not convinced this is a universally desired setting. 

I use this setting and it works well for me. I am also using a non-blinking cursor. That's probably the reason why I went with this setting at some point to avoid losing track. So far I haven't observed other issues. I wonder if it is really such an odd setting which is not meant to be customized? Do you think there are other problems with this setting?

Of course you are free to judge that the setting is so bad that you don't want to support it in your package at all.  But note that the addition is a small change, a single line. I am not asking much here. On the other hand for me personally it is not a big deal to work around this. Nothing really is, since every customization is possible in Elisp with an arbitrary amount of advices. 

> My impression here is that whoever has cursor-in-non-selected-windows=nil by default would also want to set isearch-repeat-on-direction-change=t. This is only available in Emacs 28, unfortunately.

On Emacs 28 I would maybe use `isearch-repeat-on-direction-change=t` but that's an orthogonal discussion.

**Pull request closed without merging**
